name: RHEL Build

on:
    push:
        branches:
            - rhel-ubi-build
        tags:
            - 'ubi*'
    workflow_dispatch:
        inputs:
            commit_hash:
                description: 'Commit hash to build'
                required: false
                default: 'HEAD'
    # pull_request:
    #     branches:
    #         - rhel-ubi-build

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2
          with:
            ref: ${{ github.event.inputs.commit_hash }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        
        - name: Cache rust build deps
          uses: Swatinem/rust-cache@v2
        
        - name: Build with RHEL8 UBI image
          run: |
                docker run --rm -v $(pwd):/workspace -w /workspace registry.access.redhat.com/ubi8/ubi:latest /bin/bash -c "
                    yum install -y gcc-c++ git rust cargo &&
                    export HELIX_DEFAULT_RUNTIME=/tmp/helix/runtime &&
                    export HELIX_DISABLE_AUTO_GRAMMAR_BUILD &&
                    cargo build --profile opt --locked
                    "
        # cargo build --release --path helix-term --locked

        - name: Backup artifact
          uses: actions/upload-artifact@v4
          with:
            name: helix
            path: target/opt/hx
